import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../src/pages/examples/LoginPage';

/**
 * Attempt login with empty password field
 *
 * Test Case ID: 1261
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Enter a valid email address.
   *   2. Leave the password field empty.
   *   3. Click the Login button.
 * Expected Result: Error message is displayed indicating password is required.
 * Test Data: empty_password
 * Test Data Source: dataset "valid_user" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com
 */

test.describe('Attempt login with empty password field', () => {
  test('Attempt login with empty password field', async ({ page }) => {
  // @tc:TC1261
    // Test data bound to dataset "valid_user" (representative record resolved at runtime).
    const user = getRecord("valid_user");
    
    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);
    
    // Precondition: User is on the Login page.
    await loginPage.login(user.username ?? '', user.password ?? '');
    await expect(page).toHaveURL(/inventory\.html/);
    
    // Enter a valid email address.
    await page.locator('[name="name"]').fill(user.username ?? '');
    
    // Leave the password field empty.
    await page.locator('[name="password"]').fill('');
    
    // Click the Login button.
    await page.getByRole('button', { name: 'Login' }).click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page.locator('[data-test="error"]')).toContainText('is required');
    await expect(page).toHaveURL('https://automationexercise.com');
  });
});