import { test, expect } from '@playwright/test';
import { LoginPage } from '../src/pages/examples/LoginPage';

/**
 * Attempt login with empty email field
 *
 * Test Case ID: 1260
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Leave the email field empty.
   *   2. Enter a valid password.
   *   3. Click the Login button.
 * Expected Result: Error message is displayed indicating email is required.
 * Test Data: empty_email
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com
 */

test.describe('Attempt login with empty email field', () => {
  test('Attempt login with empty email field', async ({ page }) => {
  // @tc:TC1260
    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);
    
    // Precondition: User is on the Login page.
    await loginPage.login(process.env.TEST_USERNAME ?? '', process.env.TEST_PASSWORD ?? '');
    await expect(page).toHaveURL(/inventory\.html/);
    
    // Leave the email field empty.
    await page.locator('[name="name"]').fill('');
    
    // Enter a valid password.
    await page.locator('[name="password"]').fill(process.env.TEST_PASSWORD ?? '');
    
    // Click the Login button.
    await page.getByRole('button', { name: 'Login' }).click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page.locator('[data-test="error"]')).toContainText('is required');
    await expect(page).toHaveURL('https://automationexercise.com');
  });
});