import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../src/pages/examples/LoginPage';

/**
 * Display logged-in username in navigation menu
 *
 * Test Case ID: 1255
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to the Home page after login.
 * Expected Result: Logged in as <username> is displayed in the navigation menu.
 * Test Data: valid_user
 * Test Data Source: dataset "valid_user" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com
 */

test.describe('Display logged-in username in navigation menu', () => {
  test('Display logged-in username in navigation menu', async ({ page }) => {
  // @tc:TC1255
    // Test data bound to dataset "valid_user" (representative record resolved at runtime).
    const user = getRecord("valid_user");
    
    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);
    
    // Precondition: User is successfully logged in.
    await loginPage.login(user.username ?? '', user.password ?? '');
    await expect(page).toHaveURL(/inventory\.html/);
    
    // Navigate to the Home page after login.
    await page.goto('https://automationexercise.com');
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.getByRole('link', { name: ' Products' })).toBeVisible();
  });
});