import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../src/pages/examples/LoginPage';

/**
 * Redirect to Home page after successful login
 *
 * Test Case ID: 1254
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. After clicking the Login button, wait for the redirection.
 * Expected Result: User is redirected to the Home page.
 * Test Data: valid_user
 * Test Data Source: dataset "valid_user" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com
 */

test.describe('Redirect to Home page after successful login', () => {
  test('Redirect to Home page after successful login', async ({ page }) => {
  // @tc:TC1254
    // Test data bound to dataset "valid_user" (representative record resolved at runtime).
    const user = getRecord("valid_user");
    
    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);
    
    // Precondition: User is successfully logged in.
    await loginPage.login(user.username ?? '', user.password ?? '');
    await expect(page).toHaveURL(/inventory\.html/);
    
    // After clicking the Login button, wait for the redirection.
    await page.getByRole('button', { name: 'Login' }).click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.getByRole('link', { name: ' Products' })).toBeVisible();
  });
});