import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';

/**
 * Successful login with valid credentials
 *
 * Test Case ID: 1253
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to the Login page at https://automationexercise.com/login.
   *   2. Enter a valid email address from valid_user dataset.
   *   3. Enter the corresponding valid password.
   *   4. Click the Login button.
 * Expected Result: User is successfully authenticated and redirected to the Home page.
 * Test Data: valid_user
 * Test Data Source: dataset "valid_user" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com/login./
 */

test.describe('Successful login with valid credentials', () => {
  test('Successful login with valid credentials', async ({ page }) => {
  // @tc:TC1253
    // Test data bound to dataset "valid_user" (representative record resolved at runtime).
    const user = getRecord("valid_user");
    
    // Navigate to the Login page at https://automationexercise.com/login.
    await page.goto('https://automationexercise.com/login.');
    await page.waitForLoadState('domcontentloaded');
    
    // Enter a valid email address from valid_user dataset.
    await page.locator('[name="name"]').fill(user.username ?? '');
    
    // Enter the corresponding valid password.
    await page.locator('[name="password"]').fill(user.password ?? '');
    
    // Click the Login button.
    await page.getByRole('button', { name: 'Login' }).click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.getByRole('link', { name: ' Products' })).toBeVisible();
  });
});