import { test, expect } from '@playwright/test';

/**
 * Verify search functionality with empty keyword
 *
 * Test Case ID: 1237
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Locate the search input field.
   *   2. Leave the input field empty.
   *   3. Click the Search button.
 * Expected Result: An error message is displayed indicating that the search term cannot be empty.
 * Test Data: n/a
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://automationexercise.com/
 */

test.describe('Verify search functionality with empty keyword', () => {
  test('Verify search functionality with empty keyword', async ({ page }) => {
  // @tc:TC1237
    // Locate the search input field.
    // NOTE: step not auto-mapped — review manually.
    
    // Leave the input field empty.
    // NOTE: step not auto-mapped — review manually.
    
    // Click the Search button.
    await page.getByRole('button', { name: 'Login' }).click();

    // ── Verify Expected Result ──
    await expect(page.locator('#message')).toBeVisible();
    await expect(page).toHaveURL('https://automationexercise.com/');
  });
});